export const ActionTypes = {
	SET_PRODUCTS: "SET_PRODUCTS",
	FAVORITE_PRODUCTS: "FAVORITE_PRODUCTS",
	REMOVE_PRODUCTS: "REMOVE_PRODUCTS",
};

export const VisibilityFilters = {
	SHOW_ALL: 'SHOW_ALL',
	SHOW_FAVORITE: 'SHOW_FAVORITE',
}
